global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'notification-events-api'
    scrape_interval: 5s
    static_configs:
      - targets: ['api:3000']
    metrics_path: '/metrics'